$(document).ready(
    ()=>{

    }
)

const nav = {
    ot:()=>{
        $("#mainArticle").html(pages.ot);
    },
    day01:()=>{
        $("#mainArticle").html(pages.day01);
    },
    chap19:()=>{
        $("#mainArticle").html(pages.chap19);
    },
    chap20:()=>{
        $("#mainArticle").html(pages.chap20);
    },
    chap21:()=>{
        $("#mainArticle").html(pages.chap21);
    },
    chap22:()=>{
        $("#mainArticle").html(pages.chap22);
    },
    chap23:()=>{
        $("#mainArticle").html(pages.chap23);
    },
    chap24:()=>{
        $("#mainArticle").html(pages.chap24);
    },
    chap25:()=>{
        $("#mainArticle").html(pages.chap25);
    },
    chap26:()=>{
        $("#mainArticle").html(pages.chap26);
    },
    chap27:()=>{
        $("#mainArticle").html(pages.chap27);
    },
    chap28:()=>{
        $("#mainArticle").html(pages.chap28);
    },
    chap29:()=>{
        $("#mainArticle").html(pages.chap29);
    },
    chap30:()=>{
        $("#mainArticle").html(pages.chap30);
    },
    chap31:()=>{
        $("#mainArticle").html(pages.chap31);
    },
    chap32:()=>{
        $("#mainArticle").html(pages.chap32);
    },
    chap33:()=>{
        $("#mainArticle").html(pages.chap33);
    },
    chap34:()=>{
        $("#mainArticle").html(pages.chap34);
    },
    chap35:()=>{
        $("#mainArticle").html(pages.chap35);
    }
};

const vocabs = {
    chap20:()=>{
        $("#mainArticle").html(vocab.chap20);
        funcs.practiceSentence();
    },
    chap21:()=>{
        $("#mainArticle").html(vocab.chap21);
        funcs.practiceSentence();
    },
    chap22:()=>{
        $("#mainArticle").html(vocab.chap22);
        funcs.practiceSentence();
    },
    chap23:()=>{
        $("#mainArticle").html(vocab.chap23);
        funcs.practiceSentence();
    },
    chap24:()=>{
        $("#mainArticle").html(vocab.chap24);
        funcs.practiceSentence();
    },
    chap25:()=>{
        $("#mainArticle").html(vocab.chap25);
        funcs.practiceSentence();
    },
    chap26:()=>{
        $("#mainArticle").html(vocab.chap26);
        funcs.practiceSentence();
    },
    chap27:()=>{
        $("#mainArticle").html(vocab.chap27);
        funcs.practiceSentence();
    },
    chap28:()=>{
        $("#mainArticle").html(vocab.chap28);
        funcs.practiceSentence();
    },
    chap29:()=>{
        $("#mainArticle").html(vocab.chap29);
    },
    chap30:()=>{
        $("#mainArticle").html(vocab.chap30);
    },
    chap31:()=>{
        $("#mainArticle").html(vocab.chap31);
        funcs.renderVocabList(vocab_db[0].vocabs,"list1","list2");
    },
    chap32:()=>{
        $("#mainArticle").html(vocabs.chap32);
        funcs.renderVocabList(vocab_db[1].vocabs,"list1","list2");
    },
    chap33:()=>{
        $("#mainArticle").html(vocabs.chap33);
        funcs.renderVocabList(vocab_db[2].vocabs,"list1","list2");
    },
    chap34:()=>{
        $("#mainArticle").html(vocabs.chap34);
    },
    chap35:()=>{
        $("#mainArticle").html(vocabs.chap35);
    }
}

const diary ={
    _0616:()=>{
        $("#mainArticle").html(diaries._0616);
    },
    _0617:()=>{
        $("#mainArticle").html(diaries._0617);
    },
    _0618:()=>{
        $("#mainArticle").html(diaries._0618);
    },
    _0619:()=>{
        $("#mainArticle").html(diaries._0619);
    },
    _0620:()=>{
        $("#mainArticle").html(diaries._0620);
    }
}